# Generated by Django 4.2 on 2023-04-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contactusmodel_remove_subjectsmodel_icon'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactusmodel',
            table='contact',
        ),
    ]
