# Generated by Django 4.2 on 2023-04-08 17:01

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[base.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[base.validators.validate_phone_no]),
        ),
    ]
